apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
  name: name-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v2
  template:
    metadata:
      labels:
        app: sentences
        mode: name
        version: v2
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:430d3a01a502c2b13af2619ad41f2247e6e46282e1c100db4f27c917b2867555
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_NAMES"
          value: "Athos (v2),Porthos (v2),Aramis (v2),d'Artagnan (v2)"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: name
    version: v2
  name: name-v2
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    mode: name
    version: v2
  type: ClusterIP
