apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
    version: v1
  name: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v1
  template:
    metadata:
      labels:
        app: sentences
        mode: name
        version: v1
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:430d3a01a502c2b13af2619ad41f2247e6e46282e1c100db4f27c917b2867555
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_RANDOM_SVC_URL"
          value: "http://random:5000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: name
    version: v1
  name: name
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    mode: name
    version: v1
  type: ClusterIP
