apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences-age
    mode: age
    app.kubernetes.io/part-of: sentences
  name: age
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences-age
      mode: age
      app.kubernetes.io/part-of: sentences
  template:
    metadata:
      labels:
        app: sentences-age
        mode: age
        app.kubernetes.io/part-of: sentences
      annotations:
        dummy: '123'
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:9ec280c27e4cfc88cef63866a35652e1e6238b3cbbbf4a46246343392310a31f
        name: age
        env:
        - name: "SENTENCE_MODE"
          value: "age"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences-age
    mode: age
    app.kubernetes.io/part-of: sentences
  name: age
spec:
  ports:
  - name: api
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences-age
    mode: age
  type: ClusterIP
---
