apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
  name: name-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v3
  template:
    metadata:
      labels:
        app: sentences
        mode: name
        version: v3
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:430d3a01a502c2b13af2619ad41f2247e6e46282e1c100db4f27c917b2867555
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_SVC_DELAY_MIN"
          value: "0.2"
        - name: "SENTENCE_SVC_DELAY_MAX"
          value: "0.4"
        - name: "SENTENCE_NAMES"
          value: "Pappa Carlo (v3),Flora (v3),Dorabella (v3),Granny Caramella (v3)"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: name
    version: v3
  name: name-v3
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    mode: name
    version: v3
  type: ClusterIP
