apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: age
  name: age-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: age
  template:
    metadata:
      labels:
        app: sentences
        mode: age
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:430d3a01a502c2b13af2619ad41f2247e6e46282e1c100db4f27c917b2867555
        name: age
        args:
        - /usr/src/app-grpc/sentences.py
        env:
        - name: "SENTENCE_MODE"
          value: "age"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: age
  name: age
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: grpc
  selector:
    app: sentences
    mode: age
  type: ClusterIP

